{% set name = "qiskit-ignis" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qiskit-ignis-{{ version }}.tar.gz
  sha256: 71efb17933717c0b8161a291ebd4f8d4fe8d7dfd1fdc66fa23a0b6d14fd10cf3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy >=1.13
    - python >={{ python_min }}
    - qiskit-terra >=0.15.1
    - retworkx >=0.8.0
    - scipy >=0.19,!=0.19.1
    - setuptools >=40.1.0
  run_constrained:
    - cvxpy >=1.0.15
    - matplotlib-base >=2.1
    - scikit-learn >=0.17

test:
  imports:
    - qiskit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Qiskit/qiskit-ignis
  summary: Qiskit tools for quantum information science
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - BastianZim
